### ISSUE TITLE
Reminder: Netrunner splashscreens (can be deleted)

### ISSUE THREAD

**Issue by notuxius** [blue-systems/netrunner-issues-old#125]
Steps:
1. Start System Settings app.
2. Select 'Plasma Tweaks' -> 'Splash Screen' page (notice no preview image for 'Netrunner Desktop' splash).
3. Press 'Test Splashscreen' button for 'Netrunner Desktop' splash.

Observed:
'ksplashqml' task appears in Task Manager with no fullscreen splashscreen animation.

**Comment by notuxius** [comment]
Also completely black preview image for 'Netrunner Blue' splash

**Comment by notuxius** [comment]
Pressing 'Test Splashscreen' button for 'Netrunner Default' and 'Netrunner Blue' splashscreen crashes ksplashqml

Backtrace:

```
Application: ksplashqml (ksplashqml), signal: Segmentation fault
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[Current thread is 1 (Thread 0x7f97501861c0 (LWP 4258))]

Thread 4 (Thread 0x7f9746671700 (LWP 4261)):
#0  0x00007f9755c0a739 in poll () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007f9753809e46 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f9753809f6c in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f975611bd2b in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#4  0x00007f97560c8d0b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#5  0x00007f9755f180c6 in QThread::exec() () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#6  0x00007f9755994385 in ?? () from /lib/x86_64-linux-gnu/libQt5Qml.so.5
#7  0x00007f9755f21c97 in ?? () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#8  0x00007f9755afef2a in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#9  0x00007f9755c14edf in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 3 (Thread 0x7f9746e72700 (LWP 4260)):
#0  0x00007f9755b04e6c in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00007f97474dabab in ?? () from /usr/lib/x86_64-linux-gnu/dri/i965_dri.so
#2  0x00007f97474da8d7 in ?? () from /usr/lib/x86_64-linux-gnu/dri/i965_dri.so
#3  0x00007f9755afef2a in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#4  0x00007f9755c14edf in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 2 (Thread 0x7f974ef7e700 (LWP 4259)):
#0  0x00007f9755c0a739 in poll () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007f975445fcf7 in ?? () from /lib/x86_64-linux-gnu/libxcb.so.1
#2  0x00007f975446191a in xcb_wait_for_event () from /lib/x86_64-linux-gnu/libxcb.so.1
#3  0x00007f974fd05519 in ?? () from /lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#4  0x00007f9755f21c97 in ?? () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#5  0x00007f9755afef2a in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#6  0x00007f9755c14edf in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 1 (Thread 0x7f97501861c0 (LWP 4258)):
[KCrash Handler]
#6  0x00007f97560fa7c7 in QObject::setProperty(char const*, QVariant const&) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#7  0x000056251b09f764 in ?? ()
#8  0x000056251b09e2b2 in ?? ()
#9  0x000056251b09ea18 in ?? ()
#10 0x000056251b09d916 in ?? ()
#11 0x00007f9755b3fb17 in __libc_start_main () from /lib/x86_64-linux-gnu/libc.so.6
#12 0x000056251b09d98a in _start ()
[Inferior 1 (process 4258) detached]
```

**Comment by star-buck** [comment]
we could remove all Netrunner Default, Desktop and Blue splashscreens, since we never use them or rather should all Netrunner themes set to Nosplash?
![screenshot_20181215_224340](https://user-images.githubusercontent.com/840070/50047694-ece72880-00ba-11e9-8730-d7e399d6e96b.png)

**Comment by star-buck** [comment]
seems related to this:
https://github.com/blue-systems/plasma-5.14/issues/151
